name: Run tests

permissions:
  contents: read

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
      - release/*
      - feat/*

concurrency:
  cancel-in-progress: true
  group: test-${{ github.ref }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_NAME: nestjs-cls
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}.x
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn format:check
      - run: yarn lint:check
      - run: yarn test
